### ISSUE TITLE
Biblioteka w .net standard

### ISSUE THREAD

**Issue by GetoXs** [asienicki/PESEL#19]
Hey, 
Czy jest opcja uspójnienie biblioteki do wersji framweowka .NET Standard? Z tego co widze aktualnie zbudowana jest pod .net framework 4.5.2

**Comment by asienicki** [comment]
Cześć,

Najwyższa pora :)

https://github.com/asienicki/PESEL/pull/20
https://www.nuget.org/packages/PESEL/1.0.3
